-- Migration: Add Autonomous SEO Agent Tables
-- Version: 012
-- Date: 2025-01-11
-- PRD: #0005 - Autonomous SEO Agent Dashboard

-- This migration adds all necessary tables for the autonomous SEO agent system

-- Agent Schedules Table
-- Stores scheduled tasks for the autonomous agent
CREATE TABLE IF NOT EXISTS agent_schedules (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  type TEXT NOT NULL CHECK(type IN ('audit', 'content', 'technical', 'rankings')),
  frequency TEXT NOT NULL CHECK(frequency IN ('daily', 'weekly', 'custom')),
  cron_expression TEXT,
  time TEXT,
  enabled BOOLEAN DEFAULT 1,
  companies TEXT, -- JSON array of company IDs
  config TEXT, -- JSON configuration
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Agent Alerts Table
-- Stores alerts generated by the autonomous agent
CREATE TABLE IF NOT EXISTS agent_alerts (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  type TEXT NOT NULL CHECK(type IN ('ranking_drop', 'performance_drop', 'error', 'opportunity')),
  severity TEXT NOT NULL CHECK(severity IN ('low', 'medium', 'high', 'critical')),
  company_id TEXT,
  message TEXT NOT NULL,
  data TEXT, -- JSON data
  acknowledged BOOLEAN DEFAULT 0,
  acknowledged_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- Alert Configuration Table
-- Stores user preferences for alert thresholds and channels
CREATE TABLE IF NOT EXISTS agent_alert_config (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  user_id TEXT,
  ranking_drop_threshold INTEGER DEFAULT 5,
  performance_drop_threshold INTEGER DEFAULT 20,
  channels TEXT NOT NULL, -- JSON array: ["email", "slack", "sms"]
  frequency TEXT NOT NULL CHECK(frequency IN ('immediate', 'hourly', 'daily_digest')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Company Autopilot Settings Table
-- Stores autopilot configuration per company
CREATE TABLE IF NOT EXISTS company_autopilot (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  company_id TEXT NOT NULL UNIQUE,
  enabled BOOLEAN DEFAULT 0,
  schedule TEXT DEFAULT 'daily',
  features TEXT, -- JSON array: ["audits", "content", "technical", "rankings"]
  last_run DATETIME,
  next_run DATETIME,
  stats TEXT, -- JSON statistics
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_agent_schedules_enabled ON agent_schedules(enabled);
CREATE INDEX IF NOT EXISTS idx_agent_schedules_type ON agent_schedules(type);
CREATE INDEX IF NOT EXISTS idx_agent_schedules_created ON agent_schedules(created_at);

CREATE INDEX IF NOT EXISTS idx_agent_alerts_type ON agent_alerts(type);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_severity ON agent_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_company ON agent_alerts(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_acknowledged ON agent_alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_agent_alerts_created ON agent_alerts(created_at);

CREATE INDEX IF NOT EXISTS idx_agent_alert_config_user ON agent_alert_config(user_id);

CREATE INDEX IF NOT EXISTS idx_company_autopilot_company ON company_autopilot(company_id);
CREATE INDEX IF NOT EXISTS idx_company_autopilot_enabled ON company_autopilot(enabled);

-- ROLLBACK:
-- DROP TABLE IF EXISTS agent_schedules;
-- DROP TABLE IF EXISTS agent_alerts;
-- DROP TABLE IF EXISTS agent_alert_config;
-- DROP TABLE IF EXISTS company_autopilot;
